# https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  output-dir: _site # this is the default
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "SprachLichtung"
  description: ""
  twitter-card: true
  open-graph: true
  reader-mode: true
  # page-navigation: true
  repo-branch: main
  repo-url: https://github.com/hecmec/sprachlichtung
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: "Start"
      - href: about.qmd
        text: "Über uns"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://code.com
          - text: Report a Bug
            href: https://bugs.com

  sidebar:
    style: "docked" #floating or docked
    search: true
    contents:
      - text: "Test Deutsch"
        href: website/de/0_test_de/test_de.qmd

        contents:
          - website/de/0_test_de/test_de_seite1.qmd
          - website/de/0_test_de/test_de_seite2.qmd
          - website/de/0_test_de/test_de_seite3.qmd

      - text: "Rationalität"
        href: website/de/1_rationalitaet/rationalitaet.qmd

        contents:
          - website/de/1_rationalitaet/urteilsverzerrung.qmd
          - website/de/1_rationalitaet/fehlschluesse.qmd
          - website/de/1_rationalitaet/paradoxa.qmd
          - website/de/1_rationalitaet/argumentation.qmd
          - website/de/1_rationalitaet/selbst_einklammerung.qmd

      - text: "Sprachspiele"
        href: website/de/2_sprachspiele/sprachspiele.qmd
        contents:
          - website/de/2_sprachspiele/behaupten.qmd
          - website/de/2_sprachspiele/luegen.qmd
          - website/de/2_sprachspiele/verfuehren.qmd
          - website/de/2_sprachspiele/erklaeren.qmd
          - website/de/2_sprachspiele/verstehen.qmd
          - website/de/2_sprachspiele/erzaehlen.qmd
          # - de/2_sprachspiele/unteralten.qmd
          # - de/2_sprachspiele/amüsieren.qmd
          # - de/2_sprachspiele/zuhören.qmd
          # - de/2_sprachspiele/definieren.qmd

      - text: "Gesellschaftsspiele"
        href: website/de/3_gesellschaftsspiele/gesellschaftsspiele.qmd
        contents:
          - website/de/3_gesellschaftsspiele/freiheit.qmd
          - website/de/3_gesellschaftsspiele/gleichheit.qmd
          - website/de/3_gesellschaftsspiele/solidaritaet.qmd
          - website/de/3_gesellschaftsspiele/sein_lassen.qmd
          # - de/3_gesellschaftsspiele/cooperieren.qmd
          # - de/3_gesellschaftsspiele/ausbeuten.qmd
          # - de/3_gesellschaftsspiele/versklaven.qmd
          # - de/3_gesellschaftsspiele/lieben.qmd
          # - de/3_gesellschaftsspiele/erobern.qmd

      - text: "Künstliche Welten"
        href: website/de/4_kuestlichewelten/kuenstliche_welten.qmd
        contents:
          - website/de/4_kuestlichewelten/automaten.qmd
          - website/de/4_kuestlichewelten/kuenstliche_intelligenz.qmd
          - website/de/4_kuestlichewelten/grosse_sprachmodelle.qmd
          - website/de/4_kuestlichewelten/generative_ki.qmd

      - text: "Um-welten"
        href: website/de/5_umwelten/umwelten.qmd
        contents:
          - website/de/5_umwelten/klimawandel.qmd
          - website/de/5_umwelten/verschmutzung.qmd
          - website/de/5_umwelten/klimawissenschaftler.qmd
          - website/de/5_umwelten/klimaskeptiker.qmd
          - website/de/5_umwelten/naturrechte.qmd
          - website/de/5_umwelten/tierrechte.qmd
          - website/de/5_umwelten/die_krohne_der_schoepfung.qmd

      - text: "Energien"
        href: website/de/6_energie/energien.qmd
        contents:
          - website/de/6_energie/menschenenergie.qmd
          - website/de/6_energie/tierenergie.qmd
          - website/de/6_energie/pflanzenenergie.qmd
          - website/de/6_energie/windenergie.qmd
          - website/de/6_energie/wasserenergie.qmd
          - website/de/6_energie/sonnenenergie.qmd
          - website/de/6_energie/erdwaerme.qmd
          - website/de/6_energie/nuklearenergie.qmd

      - text: "Medien-Quellen"
        href: website/de/7_medien/medien_quellen.qmd
        contents:
          - website/de/7_medien/buecher.qmd
          - website/de/7_medien/artikel.qmd
          - website/de/7_medien/videos.qmd
          - website/de/7_medien/podcasts.qmd

      - text: "Humor"
        href: website/de/8_humor/humor.qmd
        contents:
          - website/de/8_humor/memes.qmd
          - website/de/8_humor/humor_zitate.qmd
          - website/de/8_humor/humor_witze.qmd
          - website/de/8_humor/humor_filme.qmd
# metadata-files:
#   - sidebar.yml

