# https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  output-dir: _site # this is the default
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "SprachLichtung"
  description: "Learn Deep Learning with fastai and PyTorch, 2022"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: main
  repo-url: https://github.com/hecmec/sprachlichtung
  repo-actions: [issue]  
  navbar:
    left:
      - href: index.qmd
        text: "Heimat"
      - href: about.qmd
        text: "Über uns"
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com

  sidebar:
    style: "floating" #floating or docked
    search: true
    contents:
      - text: "Rationalität"
        href: website/de/1_rationalitaet/rationalitaet.qmd

        contents:
          - website/de/1_rationalitaet/urteilsverzerrung.qmd
          - website/de/1_rationalitaet/fehlschluesse.qmd
          - website/de/1_rationalitaet/paradoxa.qmd
          - website/de/1_rationalitaet/argumentation.qmd
          - website/de/1_rationalitaet/selbst_einklammerung.qmd

      - text: "Sprachspiele"
        href: website/de/2_sprachspiele/sprachspiele.qmd
        contents:
          - website/de/2_sprachspiele/behaupten.qmd
          - website/de/2_sprachspiele/lügen.qmd
          - website/de/2_sprachspiele/verführen.qmd
          - website/de/2_sprachspiele/erklären.qmd
          - website/de/2_sprachspiele/verstehen.qmd
          - website/de/2_sprachspiele/erzählen.qmd
          # - de/2_sprachspiele/unteralten.qmd
          # - de/2_sprachspiele/amüsieren.qmd
          # - de/2_sprachspiele/zuhören.qmd
          # - de/2_sprachspiele/definieren.qmd

      - text: "Gesellschaftsspiele"
        href: website/de/3_gesellschaftsspiele/gesellschaftsspiele.qmd
        contents:
          - website/de/3_gesellschaftsspiele/freiheit.qmd
          - website/de/3_gesellschaftsspiele/gleichheit.qmd
          - website/de/3_gesellschaftsspiele/solidarität.qmd
          - website/de/3_gesellschaftsspiele/Sein_lassen.qmd
          # - de/3_gesellschaftsspiele/cooperieren.qmd
          # - de/3_gesellschaftsspiele/ausbeuten.qmd
          # - de/3_gesellschaftsspiele/versklaven.qmd
          # - de/3_gesellschaftsspiele/lieben.qmd
          # - de/3_gesellschaftsspiele/erobern.qmd

      - text: "Künstliche Welten"
        href: website/de/4_kuestlichewelten/künstliche_welten.qmd
        contents:
          - website/de/4_kuestlichewelten/automaten.qmd
          - website/de/4_kuestlichewelten/künstliche_intelligenz.qmd
          - website/de/4_kuestlichewelten/grosse_sprachmodelle.qmd
          - website/de/4_kuestlichewelten/generative_ki.qmd

      - text: "Um-welten"
        href: website/de/5_umwelten/umwelten.qmd
        contents:
          - website/de/5_umwelten/klimawandel.qmd
          - website/de/5_umwelten/verschmutzung.qmd
          - website/de/5_umwelten/klimawissenschaftler.qmd
          - website/de/5_umwelten/klimaskeptiker.qmd
          - website/de/5_umwelten/naturrechte.qmd
          - website/de/5_umwelten/tierrechte.qmd
          - website/de/5_umwelten/die_krohne_der_schoepfung.qmd

      - text: "Energien"
        href: website/de/6_Energie/energien.qmd
        contents:
          - website/de/6_Energie/menschenenergie.qmd
          - website/de/6_Energie/tierenergie.qmd
          - website/de/6_Energie/pflanzenenergie.qmd
          - website/de/6_Energie/windenergie.qmd
          - website/de/6_Energie/wasserenergie.qmd
          - website/de/6_Energie/sonnenenergie.qmd
          - website/de/6_Energie/erdwärme.qmd
          - website/de/6_Energie/nuklearenergie.qmd

      - text: "Medien-Quellen"
        href: website/de/7_Medien/medien_quellen.qmd
        contents:
          - website/de/7_Medien/buecher.qmd
          - website/de/7_Medien/artikel.qmd
          - website/de/7_Medien/videos.qmd
          - website/de/7_Medien/podcasts.qmd

      - text: "Humor"
        href: website/de/8_Humor/humor.qmd
        contents:
          - website/de/8_Humor/memes.qmd
          - website/de/8_Humor/humor_zitate.qmd
          - website/de/8_Humor/humor_witze.qmd
          - website/de/8_Humor/humor_filme.qmd

# metadata-files:
#   - sidebar.yml

