backend:
  name: github
  repo: hecmec/sprachlichtung
  branch: main

media_folder: static/img/uploads
public_folder: /sprachlichtung/img/uploads

collections:
  - name: kritisches-denken
    label: "Kritisches Denken (DE)"
    folder: docs/kritisches-denken
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: "Sidebar position", name: sidebar_position, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: kritisches-denken-en
    label: "Kritisches Denken (EN translation)"
    folder: i18n/en/docusaurus-plugin-content-docs/current/kritisches-denken
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: "Sidebar position", name: sidebar_position, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: sprach-welten
    label: "Sprach-Welten (DE)"
    folder: docs/sprach-welten
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: "Sidebar position", name: sidebar_position, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: sprach-welten-en
    label: "Sprach-Welten (EN translation)"
    folder: i18n/en/docusaurus-plugin-content-docs/current/sprach-welten
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: "Sidebar position", name: sidebar_position, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: markdown }
